// Postgres access for orders. One pooled connection reused across warm
// serverless invocations; all queries are parameterized.

import { Pool, type QueryResultRow } from "pg";

const globalForPg = globalThis as unknown as { __pgPool?: Pool };

function makePool(): Pool {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error(
      "DATABASE_URL is not set. Add your Postgres connection string.",
    );
  }
  const useSSL =
    process.env.DATABASE_SSL === "true" ||
    (/sslmode=require|neon\.tech|supabase|pooler|render\.com|vercel/.test(
      connectionString,
    ) &&
      process.env.DATABASE_SSL !== "false");

  return new Pool({
    connectionString,
    ssl: useSSL ? { rejectUnauthorized: false } : undefined,
    max: 5,
  });
}

export function getPool(): Pool {
  if (!globalForPg.__pgPool) globalForPg.__pgPool = makePool();
  return globalForPg.__pgPool;
}

export async function query<T extends QueryResultRow = QueryResultRow>(
  text: string,
  params: unknown[] = [],
): Promise<{ rows: T[]; rowCount: number }> {
  const res = await getPool().query<T>(text, params);
  return { rows: res.rows, rowCount: res.rowCount ?? 0 };
}

let schemaReady: Promise<void> | null = null;

export function ensureSchema(): Promise<void> {
  if (!schemaReady) schemaReady = initSchema();
  return schemaReady;
}

async function initSchema(): Promise<void> {
  await getPool().query(`
    CREATE TABLE IF NOT EXISTS orders (
      id              BIGSERIAL PRIMARY KEY,
      idempotency_key TEXT UNIQUE,
      track_token     TEXT NOT NULL,
      notes           TEXT NOT NULL DEFAULT '',
      discount        NUMERIC(14,2) NOT NULL DEFAULT 0,
      grand_total     NUMERIC(14,2) NOT NULL DEFAULT 0,
      status          TEXT NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','approved')),
      created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS order_items (
      id           BIGSERIAL PRIMARY KEY,
      order_id     BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      product_id   INTEGER,
      product_code TEXT NOT NULL,
      product_name TEXT NOT NULL,
      quantity     INTEGER NOT NULL DEFAULT 1,
      unit_price   NUMERIC(14,2) NOT NULL DEFAULT 0,
      subtotal     NUMERIC(14,2) NOT NULL DEFAULT 0,
      is_free      BOOLEAN NOT NULL DEFAULT false
    );

    -- The catalog. It used to live in each visitor's IndexedDB, which meant an
    -- admin's edits never left the browser that made them. Here it is shared:
    -- the admin writes, every visitor reads. Seeded once from the bundled
    -- data/catalog.json (see seedCatalog in lib/catalog.ts); after that the
    -- database is the source of truth and the JSON file is only a fallback for
    -- an empty database.
    CREATE TABLE IF NOT EXISTS categories (
      id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name          TEXT NOT NULL,
      name_ar       TEXT NOT NULL DEFAULT '',
      display_order INTEGER NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS products (
      id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name           TEXT NOT NULL,
      code           TEXT NOT NULL UNIQUE,
      price          NUMERIC(14,2) NOT NULL DEFAULT 0,
      image_url      TEXT NOT NULL DEFAULT '',
      category_id    INTEGER NOT NULL REFERENCES categories(id),
      description    TEXT NOT NULL DEFAULT '',
      benefits       TEXT NOT NULL DEFAULT '',
      ingredients    TEXT NOT NULL DEFAULT '',
      "usage"        TEXT NOT NULL DEFAULT '',
      name_ar        TEXT NOT NULL DEFAULT '',
      description_ar TEXT NOT NULL DEFAULT '',
      benefits_ar    TEXT NOT NULL DEFAULT '',
      ingredients_ar TEXT NOT NULL DEFAULT '',
      usage_ar       TEXT NOT NULL DEFAULT '',
      -- NULL means this product's stock isn't tracked, so it stays
      -- purchasable. 0 means genuinely out of stock. See isOutOfStock().
      stock          INTEGER
    );

    CREATE INDEX IF NOT EXISTS idx_products_category ON products (category_id);

    CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);

    -- Who placed the order and where it goes. Added after the first orders
    -- were taken, so they default to empty rather than being NOT NULL from
    -- the start; the storefront asks for all three before it will submit.
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_name TEXT NOT NULL DEFAULT '';
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_phone TEXT NOT NULL DEFAULT '';
    ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_location TEXT NOT NULL DEFAULT '';

    -- The pharmacy directory and its visit map were removed from the admin.
    -- Their tables are deliberately left alone rather than dropped here: a
    -- schema bootstrap is the wrong place to destroy data someone typed in.
    -- Drop pharmacies and pharmacy_folders by hand if you want the space.
  `);
}
